const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',

    //admin
    /* ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
    ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT', */

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //ADMIN
    GET_GENDER_START: 'GET_GENDER_START',
    GET_GENDER_SUCCESS: 'GET_GENDER_SUCCESS',
    GET_GENDER_FAIL: 'GET_GENDER_FAIL',

    GET_POSITION_START: 'GET_POSITION_START',
    GET_POSITION_SUCCESS: 'GET_POSITION_SUCCESS',
    GET_POSITION_FAIL: 'GET_POSITION_FAIL',

    GET_ROLE_START: 'GET_ROLE_START',
    GET_ROLE_SUCCESS: 'GET_ROLE_SUCCESS',
    GET_ROLE_FAIL: 'GET_ROLE_FAIL',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAIL: 'CREATE_USER_FAIL',

    GET_ALL_USER_SUCCESS: 'GET_ALL_USER_SUCCESS',
    GET_ALL_USER_FAIL: 'GET_ALL_USER_FAIL',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAIL: 'DELETE_USER_FAIL',

    GET_ONE_USER_SUCCESS: 'GET_ONE_USER_SUCCESS',
    GET_ONE_USER_FAIL: 'GET_ONE_USER_FAIL',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAIL: 'UPDATE_USER_FAIL',

    GET_ROLE_DATA_SUCCESS: 'GET_ROLE_DATA_SUCCESS',
    GET_ROLE_DATA_FAIL: 'GET_ROLE_DATA_FAIL',

    CREATE_MARKDOWN_SUCCESS: 'CREATE_MARKDOWN_SUCCESS',
    CREATE_MARKDOWN_FAIL: 'CREATE_MARKDOWN_FAIL',

    GET_DETAIL_SUCCESS: 'GET_DETAIL_SUCCESS',
    GET_DETAIL_FAIL: 'GET_DETAIL_FAIL',
})

export default actionTypes;